/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TodoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTask"
      | "getTask"
      | "getTaskCount"
      | "tasks"
      | "toggleTask"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TaskAdded"): EventFragment;

  encodeFunctionData(functionFragment: "addTask", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "toggleTask",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toggleTask", data: BytesLike): Result;
}

export namespace TaskAddedEvent {
  export type InputTuple = [text: string];
  export type OutputTuple = [text: string];
  export interface OutputObject {
    text: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Todo extends BaseContract {
  connect(runner?: ContractRunner | null): Todo;
  waitForDeployment(): Promise<this>;

  interface: TodoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTask: TypedContractMethod<[_text: string], [void], "nonpayable">;

  getTask: TypedContractMethod<
    [_index: BigNumberish],
    [[string, boolean]],
    "view"
  >;

  getTaskCount: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { text: string; completed: boolean }],
    "view"
  >;

  toggleTask: TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTask"
  ): TypedContractMethod<[_text: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<[_index: BigNumberish], [[string, boolean]], "view">;
  getFunction(
    nameOrSignature: "getTaskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { text: string; completed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggleTask"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "TaskAdded"
  ): TypedContractEvent<
    TaskAddedEvent.InputTuple,
    TaskAddedEvent.OutputTuple,
    TaskAddedEvent.OutputObject
  >;

  filters: {
    "TaskAdded(string)": TypedContractEvent<
      TaskAddedEvent.InputTuple,
      TaskAddedEvent.OutputTuple,
      TaskAddedEvent.OutputObject
    >;
    TaskAdded: TypedContractEvent<
      TaskAddedEvent.InputTuple,
      TaskAddedEvent.OutputTuple,
      TaskAddedEvent.OutputObject
    >;
  };
}
